<nav class="navbar navbar-inverse" role="navigation">
    <ul class="nav navbar-nav nn-custom">
        <li class="active">
            <a id="nn_button_save" href="javascript:;">Save</a>
        </li>
        <li>
            <a class="nn-custom-button" data-nn-tag="h1" href="javascript:;">H1</a>
        </li>
        <li>
            <a class="nn-custom-button" data-nn-tag="h2" href="javascript:;">H2</a>
        </li>
        <li>
            <a class="nn-custom-button" data-nn-tag="ul" href="javascript:;">Ul</a>
        </li>
        <li>
            <a class="nn-custom-button" data-nn-tag="ol" href="javascript:;">Ol</a>
        </li>
        <li>
            <a class="nn-custom-button" data-nn-tag="dl" href="javascript:;">Dl</a>
        </li>
    </ul>
</nav>