<div class="col-xs-12">
    <?php echo $fileName; ?>
    <form method="POST" >
        <textarea id="editor" rows="30" cols="150"><?php echo $fileContent; ?></textarea>
        <br />
        <input type="submit" value="save" class="btn btn-primary" />
    </form>
</div>



<script>
    var baseCurrentMode = '<?php echo $currentMode;?>';
</script>
<style>
    .ace_editor {
        width: 100%;
        height: 400px;
    }
</style>