<nav class="navbar navbar-inverse" role="navigation">
    <ul class="nav navbar-nav">
        <li class="active nn-custom">
            <a id="nn_button_save" href="javascript:;">Save</a>
        </li>
        <li class="nn-custom">
            <a class="nn-custom-button" data-nn-tag="h1" href="javascript:;">H1</a>
        </li>
        <li class="nn-custom">
            <a class="nn-custom-button" data-nn-tag="h2" href="javascript:;">H2</a>
        </li>
    </ul>
</nav>